In [2]:
import numpy as np
a = np.array([0.3, 2.9, 4.0])
exp_a = np.exp(a) # e의 지수함수 꼴로 배열을 바꿔주는 것
print(exp_a)

sum_exp_a = np.sum(exp_a) # 지수함수들의 합
print(sum_exp_a)

y = exp_a / sum_exp_a
print(y)

[ 1.34985881 18.17414537 54.59815003]
74.1221542101633
[0.01821127 0.24519181 0.73659691]


In [3]:
def softmax(a):
    exp_a = np.exp(a)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    
    return y

In [6]:
a = np.array([1010, 1000, 990])
b = np.exp(a) / np.sum(np.exp(a))
print(b)

c = np.max(a)
print(a-c)

d = np.exp(a-c) / np.sum(np.exp(a-c))
print(d)

[nan nan nan]
[  0 -10 -20]
[9.99954600e-01 4.53978686e-05 2.06106005e-09]


C:\Users\유민준\AppData\Local\Temp\ipykernel_13324\1820336010.py:2: RuntimeWarning: overflow encountered in exp
  b = np.exp(a) / np.sum(np.exp(a))
C:\Users\유민준\AppData\Local\Temp\ipykernel_13324\1820336010.py:2: RuntimeWarning: invalid value encountered in divide
  b = np.exp(a) / np.sum(np.exp(a))


In [7]:
# overflow문제를 해결한 softmax 함수
def softmax(a):
    c = np.max(a)
    exp_a = np.exp(a-c)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    
    return y